version: "3.9"

services:
  postgresql:
    image: arm64v8/postgres:latest
    environment:
      - POSTGRES_PASSWORD=rootroot
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - default

  mongodb:
    image: arm64v8/mongo:latest
    environment:
      - MONGODB_USER=chenyifan
      - MONGODB_PASS=password
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - default

  redis:
    image: arm64v8/redis:latest
    expose:
      - 6380
    ports:
      - "6380:6380"
    networks:
      - default